// <auto-generated />
using System;
using AxisModa.Ecommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AxisModa.Ecommerce.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723165934_AjustaImagensParaLocais")]
    partial class AjustaImagensParaLocais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AxisModa.Ecommerce.Domain.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Subcategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f8c7bcf-6f68-459b-a7b8-a733370f2cb7"),
                            Ativo = true,
                            Categoria = "Masculino",
                            DataCriacao = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Camisa de linho respiravel com corte classico.",
                            Estoque = 25,
                            ImagemUrl = "/uploads/produtos/camisa.jpg",
                            Nome = "Camisa Linho Comfort",
                            Preco = 189.90m,
                            Subcategoria = "Camisa"
                        },
                        new
                        {
                            Id = new Guid("60762f4d-bc3f-4221-b306-e5f7ba2920e9"),
                            Ativo = true,
                            Categoria = "Feminino",
                            DataCriacao = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Vestido de seda premium fluido para ocasioes especiais.",
                            Estoque = 18,
                            ImagemUrl = "/uploads/produtos/vestido.jpg",
                            Nome = "Vestido Seda Midi",
                            Preco = 349.90m,
                            Subcategoria = "Vestido"
                        },
                        new
                        {
                            Id = new Guid("aeaaec9f-a407-4909-b6c9-a65f7356a263"),
                            Ativo = true,
                            Categoria = "Infantil",
                            DataCriacao = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Conjunto super confortavel de camiseta e shorts.",
                            Estoque = 40,
                            ImagemUrl = "/uploads/produtos/infantil.jpg",
                            Nome = "Conjunto Infantil Algodao",
                            Preco = 99.90m,
                            Subcategoria = "Conjunto"
                        },
                        new
                        {
                            Id = new Guid("bb98a8d4-4e0e-46db-bef6-56cc77ecf145"),
                            Ativo = true,
                            Categoria = "Feminino",
                            DataCriacao = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Blusa cropped de malha com toque macio.",
                            Estoque = 32,
                            ImagemUrl = "/uploads/produtos/blusa.jpg",
                            Nome = "Blusa Cropped Urban",
                            Preco = 79.90m,
                            Subcategoria = "Blusa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
